<a href="https://colab.research.google.com/github/Abhinavanand56/Machine-Learning-Notebook/blob/main/Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages in Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster Operations

In [4]:
import numpy as np

In [5]:
#list vs numpy time taken
from time import process_time

In [8]:
#time taken by a list
python_list = [i for i in range(1000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.08068630100000007


In [11]:
np_array = np.array([i for i in range(1000000)])

start_time  = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0011945909999973026


In [12]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [14]:
#creating a 1D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [15]:
a.shape

(5,)

In [16]:
b =  np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
b.shape

(2, 4)

In [18]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [20]:
#Initial palceholders in aaray
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
z = np.full((5,4),3)
print(z)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [27]:
#creating a indentity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#create  a numpy array of random values
b = np.random.random((3,4))
print(b)

[[0.37372262 0.85296145 0.3602293  0.36478985]
 [0.3673962  0.49713163 0.35882137 0.89590399]
 [0.77723841 0.96152158 0.93027867 0.39838867]]


In [11]:
#random integer values within a specific range
c = np.random.randint(10,120,(3,5))
print(c)

[[ 35  24 101 106  92]
 [ 40  80  36 101  34]
 [ 24  39  56  89  95]]


In [14]:
#array fo evenly spaced values
d = np.linspace(10,30,9)

In [15]:
print(d)

[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30. ]


In [6]:
#cinverting a list to numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [8]:
#Analysing a numpy array
c = np.random.randint(10,90,(5,5))
print(c)

[[40 32 50 85 35]
 [77 37 56 69 10]
 [34 60 58 87 15]
 [89 48 79 78 72]
 [76 13 80 69 57]]


In [9]:
#array dimension
print(c.shape)

(5, 5)


In [10]:
#no. of dimension
print(c.ndim)

2


In [11]:
#checking the number of elements in an aaray
print(c.size)

25


In [12]:
#checking the data type present in the array
print(c.dtype)

int64


In [13]:
#Mathematical Operations on np aaray
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # + sign will concatenate or join the two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [14]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
#thing to notice random integer values can be of same values in a np array same values

[[8 2 4]
 [7 3 7]
 [1 7 7]]
[[12 16 10]
 [11 17 11]
 [12 11 18]]


In [16]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 18 14]
 [18 20 18]
 [13 18 25]]
[[ -4 -14  -6]
 [ -4 -14  -4]
 [-11  -4 -11]]
[[ 96  32  40]
 [ 77  51  77]
 [ 12  77 126]]
[[0.66666667 0.125      0.4       ]
 [0.63636364 0.17647059 0.63636364]
 [0.08333333 0.63636364 0.38888889]]


In [19]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[3 0 0]
 [4 0 7]
 [9 8 6]]
[[19 19 15]
 [11 18 17]
 [13 15 11]]
[[22 19 15]
 [15 18 24]
 [22 23 17]]
[[-16 -19 -15]
 [ -7 -18 -10]
 [ -4  -7  -5]]
[[ 57   0   0]
 [ 44   0 119]
 [117 120  66]]
[[0.15789474 0.         0.        ]
 [0.36363636 0.         0.41176471]
 [0.69230769 0.53333333 0.54545455]]


In [23]:
#array manipulation
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 9 7]
 [8 4 7]]
(2, 3)


In [24]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 8]
 [9 4]
 [7 7]]
(3, 2)


In [25]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 8]
 [9 4]
 [7 7]]
(3, 2)


In [26]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 5 5]
 [9 7 8]]
(2, 3)


In [29]:
b = a.reshape(1,6)
print(b)
print(b.shape)

[[2 5 5 9 7 8]]
(1, 6)
